// Package config loads, validates and persists the local JSON configuration
// for the print agent.
//
// The configuration file lives next to the binary (./configs/printers.json
// by default) and can be overridden with the PRINT_AGENT_CONFIG environment
// variable. A fresh agent generates a printers.example.json on first run
// if no file is found, so operators can copy it and edit.
package config

import (
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sync"
	"time"
)

// Tenant identifies the SaaS tenant/branch the agent serves. Used in /health
// and in the dashboard so operators can confirm they pointed the agent at
// the right place.
type Tenant struct {
	ID       string `json:"id"`
	BranchID string `json:"branch_id"`
}

// Printer describes one physical printer reachable by the agent.
//
// Type values:
//   - "network": direct TCP socket, typically port 9100 (raw ESC/POS).
//   - "usb":     print via the OS spooler (CUPS / Windows Spooler).
//   - "file":    debug mode, writes the generated bytes to a file on disk.
type Printer struct {
	ID           string `json:"id"`
	Name         string `json:"name"`
	Type         string `json:"type"`
	Host         string `json:"host,omitempty"`
	Port         int    `json:"port,omitempty"`
	SystemName   string `json:"system_name,omitempty"`
	FilePath     string `json:"file_path,omitempty"`
	CodePage     string `json:"code_page"`
	CharsPerLine int    `json:"chars_per_line"`
	Cut          string `json:"cut"`
}

// Queue holds the retry policy for failed jobs.
type Queue struct {
	MaxRetries     int           `json:"max_retries"`
	RetryBackoffMs []int         `json:"retry_backoff_ms"`
	DedupWindow    time.Duration `json:"-"`
	DedupWindowMs  int           `json:"dedup_window_ms"`
}

// Panel is the local web panel configuration.
type Panel struct {
	Enabled bool   `json:"enabled"`
	PIN     string `json:"pin"`
}

// Config is the root of the JSON file.
type Config struct {
	Port     int       `json:"port"`
	Bind     string    `json:"bind"`
	Tenant   Tenant    `json:"tenant"`
	Printers []Printer `json:"printers"`
	Queue    Queue     `json:"queue"`
	Panel    Panel     `json:"panel"`
}

// Default returns a starter configuration that the agent writes on first
// run if no file is found. It is meant to be a template, not production.
func Default() Config {
	return Config{
		Port: 4510,
		Bind: "127.0.0.1",
		Tenant: Tenant{
			ID:       "tenant_default",
			BranchID: "branch_default",
		},
		Printers: []Printer{
			{
				ID:           "cocina",
				Name:         "Cocina",
				Type:         "network",
				Host:         "192.168.1.30",
				Port:         9100,
				CodePage:     "cp850",
				CharsPerLine: 42,
				Cut:          "partial",
			},
		},
		Queue: Queue{
			MaxRetries:     3,
			RetryBackoffMs: []int{1000, 3000, 10000},
			DedupWindowMs:  300000,
		},
		Panel: Panel{
			Enabled: true,
			PIN:     "0000",
		},
	}
}

// Store wraps a Config with thread-safe access and disk reload.
type Store struct {
	mu   sync.RWMutex
	path string
	cfg  Config
}

// Load reads the JSON config from path. If the file does not exist and
// create is true, the default config is written to disk and returned.
// If the file is invalid, an error is returned and the in-memory state
// is left untouched.
func Load(path string, create bool) (*Store, error) {
	data, err := os.ReadFile(path)
	if errors.Is(err, os.ErrNotExist) {
		if !create {
			return nil, fmt.Errorf("config file %q not found", path)
		}
		cfg := Default()
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			return nil, fmt.Errorf("create config dir: %w", err)
		}
		b, err := json.MarshalIndent(cfg, "", "  ")
		if err != nil {
			return nil, fmt.Errorf("marshal default config: %w", err)
		}
		if err := os.WriteFile(path, b, 0o644); err != nil {
			return nil, fmt.Errorf("write default config: %w", err)
		}
		return &Store{path: path, cfg: cfg}, nil
	}
	if err != nil {
		return nil, fmt.Errorf("read config: %w", err)
	}
	var cfg Config
	if err := json.Unmarshal(data, &cfg); err != nil {
		return nil, fmt.Errorf("parse config: %w", err)
	}
	cfg.Queue.DedupWindow = time.Duration(cfg.Queue.DedupWindowMs) * time.Millisecond
	if err := cfg.Validate(); err != nil {
		return nil, fmt.Errorf("validate config: %w", err)
	}
	return &Store{path: path, cfg: cfg}, nil
}

// Get returns a snapshot of the current configuration.
func (s *Store) Get() Config {
	s.mu.RLock()
	defer s.mu.RUnlock()
	return s.cfg
}

// Path returns the on-disk path the Store loaded from.
func (s *Store) Path() string {
	return s.path
}

// Reload re-reads the file from disk and validates it. On error the
// in-memory config is left untouched and the error is returned.
func (s *Store) Reload() error {
	data, err := os.ReadFile(s.path)
	if err != nil {
		return fmt.Errorf("read config: %w", err)
	}
	var cfg Config
	if err := json.Unmarshal(data, &cfg); err != nil {
		return fmt.Errorf("parse config: %w", err)
	}
	cfg.Queue.DedupWindow = time.Duration(cfg.Queue.DedupWindowMs) * time.Millisecond
	if err := cfg.Validate(); err != nil {
		return fmt.Errorf("validate config: %w", err)
	}
	s.mu.Lock()
	s.cfg = cfg
	s.mu.Unlock()
	return nil
}

// Replace swaps the in-memory config with the provided one, then writes it
// to disk. Used by PUT /config.
func (s *Store) Replace(cfg Config) error {
	cfg.Queue.DedupWindow = time.Duration(cfg.Queue.DedupWindowMs) * time.Millisecond
	if err := cfg.Validate(); err != nil {
		return err
	}
	b, err := json.MarshalIndent(cfg, "", "  ")
	if err != nil {
		return fmt.Errorf("marshal config: %w", err)
	}
	if err := os.WriteFile(s.path, b, 0o644); err != nil {
		return fmt.Errorf("write config: %w", err)
	}
	s.mu.Lock()
	s.cfg = cfg
	s.mu.Unlock()
	return nil
}

// Validate enforces required fields and supported values. Called on load
// and on every PUT /config.
func (c Config) Validate() error {
	if c.Port <= 0 || c.Port > 65535 {
		return fmt.Errorf("port must be between 1 and 65535, got %d", c.Port)
	}
	if c.Bind == "" {
		return errors.New("bind is required")
	}
	if len(c.Printers) == 0 {
		return errors.New("at least one printer is required")
	}
	seen := make(map[string]struct{}, len(c.Printers))
	for i, p := range c.Printers {
		if p.ID == "" {
			return fmt.Errorf("printers[%d]: id is required", i)
		}
		if _, dup := seen[p.ID]; dup {
			return fmt.Errorf("printers[%d]: duplicate id %q", i, p.ID)
		}
		seen[p.ID] = struct{}{}
		switch p.Type {
		case "network":
			if p.Host == "" || p.Port <= 0 {
				return fmt.Errorf("printers[%d] (%s): network requires host and port", i, p.ID)
			}
		case "usb":
			if p.SystemName == "" {
				return fmt.Errorf("printers[%d] (%s): usb requires system_name", i, p.ID)
			}
		case "file":
			if p.FilePath == "" {
				return fmt.Errorf("printers[%d] (%s): file requires file_path", i, p.ID)
			}
		default:
			return fmt.Errorf("printers[%d] (%s): unknown type %q", i, p.ID, p.Type)
		}
		if p.Cut != "" && p.Cut != "partial" && p.Cut != "full" && p.Cut != "none" {
			return fmt.Errorf("printers[%d] (%s): cut must be partial, full or none", i, p.ID)
		}
	}
	if c.Queue.MaxRetries < 0 {
		return fmt.Errorf("queue.max_retries must be >= 0")
	}
	return nil
}
